import { shouldIgnore } from './locCounter.js';

/**
 * Extracts key API signatures, classes, interfaces, and function headers from source code
 * @param {string} filename - File path
 * @param {string} content - Raw source code string
 * @returns {string[]} List of signature lines
 */
export function extractSignatures(filename, content) {
  if (!content || typeof content !== 'string') return [];

  const lines = content.split('\n');
  const signatures = [];

  const ext = filename.split('.').pop().toLowerCase();

  for (let line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('//') || trimmed.startsWith('#') || trimmed.startsWith('/*')) {
      continue;
    }

    // 1. JavaScript / TypeScript
    if (ext === 'js' || ext === 'ts' || ext === 'jsx' || ext === 'tsx' || ext === 'mjs') {
      if (
        /^export\s+(default\s+)?(async\s+)?function\s+/i.test(trimmed) ||
        /^export\s+(default\s+)?class\s+/i.test(trimmed) ||
        /^export\s+(interface|type)\s+/i.test(trimmed) ||
        /^export\s+const\s+\w+\s*=\s*(\(|async)/i.test(trimmed)
      ) {
        signatures.push(trimmed.replace(/\{.*$/, '').trim());
      }
    }

    // 2. Python
    else if (ext === 'py') {
      if (/^(class\s+\w+|def\s+\w+)/.test(trimmed)) {
        signatures.push(trimmed.replace(/:.*$/, '').trim());
      }
    }

    // 3. Go
    else if (ext === 'go') {
      if (/^(func\s+(\([^)]+\)\s+)?\w+|type\s+\w+\s+(struct|interface))/.test(trimmed)) {
        signatures.push(trimmed.replace(/\{.*$/, '').trim());
      }
    }

    // 4. Rust
    else if (ext === 'rs') {
      if (/^pub\s+(async\s+)?(fn|struct|enum|trait)\s+/i.test(trimmed)) {
        signatures.push(trimmed.replace(/\{.*$/, '').trim());
      }
    }
  }

  return signatures;
}

/**
 * Generates an architectural skeleton of the repository for LLM context injection
 * @param {string} repoName - Repository name (e.g. owner/repo)
 * @param {string[]} files - List of relative file paths
 * @param {Function} readFile - (path) => string
 * @returns {string} Markdown document
 */
export function generateSkeleton(repoName, files, readFile) {
  const cleanFiles = files.filter(f => !shouldIgnore(f));
  const output = [];

  output.push(`# ARCHITECTURE SKELETON: ${repoName}`);
  output.push(`Generated by Repo-Lens | Total Tracked Source Files: ${cleanFiles.length}\n`);

  output.push(`## 📁 File Tree Overview\n\`\`\``);
  for (const f of cleanFiles.slice(0, 50)) {
    output.push(`├── ${f}`);
  }
  if (cleanFiles.length > 50) {
    output.push(`└── ... (${cleanFiles.length - 50} more files)`);
  }
  output.push('```\n');

  output.push(`## 🧩 Key Signatures & Exported Interfaces\n`);

  for (const f of cleanFiles) {
    const ext = f.split('.').pop().toLowerCase();
    if (!['js', 'ts', 'jsx', 'tsx', 'py', 'go', 'rs'].includes(ext)) {
      continue;
    }

    let content = '';
    try {
      content = readFile(f) || '';
    } catch {
      continue;
    }

    const sigs = extractSignatures(f, content);
    if (sigs.length > 0) {
      output.push(`### \`${f}\``);
      output.push('```' + ext);
      for (const sig of sigs) {
        output.push(sig);
      }
      output.push('```\n');
    }
  }

  return output.join('\n');
}
